title: "SIG: Game intelligence"
description: "A Special Interest Group for AI in Games, Game AI research, and practical game intelligence."

url: "https://thapanapongrukkanunt.github.io"
baseurl: "/csgame"

#url: ""
#baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: dark
logo: "/assets/img/logo.svg"

markdown: kramdown
permalink: pretty

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  events:
    output: true
    permalink: /events/:name/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single

  - scope:
      path: ""
      type: events
    values:
      layout: single

  - scope:
      path: ""
      type: pages
    values:
      layout: single
